
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.gochiken.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.gochiken.item.ZnicIngotItem;
import net.mcreator.gochiken.item.ZnicChickenSeedItem;
import net.mcreator.gochiken.item.ZnicChickenItem;
import net.mcreator.gochiken.item.YellowChikenItem;
import net.mcreator.gochiken.item.XpChickenSeedItem;
import net.mcreator.gochiken.item.XpChickenItem;
import net.mcreator.gochiken.item.WhiteChickenSeedItem;
import net.mcreator.gochiken.item.WaterChickenSeedItem;
import net.mcreator.gochiken.item.WaterChickenItem;
import net.mcreator.gochiken.item.StringChickenSeedItem;
import net.mcreator.gochiken.item.StringChickenItem;
import net.mcreator.gochiken.item.SnowballItem;
import net.mcreator.gochiken.item.SnowbakkChickenSeedItem;
import net.mcreator.gochiken.item.SlimeChickenSeedItem;
import net.mcreator.gochiken.item.SilmeChikenItem;
import net.mcreator.gochiken.item.SealanternChickenSeedItem;
import net.mcreator.gochiken.item.SealanternChickenItem;
import net.mcreator.gochiken.item.SandChokenItem;
import net.mcreator.gochiken.item.SandChickenSeedItem;
import net.mcreator.gochiken.item.RottenFleshBagItem;
import net.mcreator.gochiken.item.RedstoneChikenItem;
import net.mcreator.gochiken.item.RedStoneChickenSeedItem;
import net.mcreator.gochiken.item.RedChikenItem;
import net.mcreator.gochiken.item.RLogChickenSeedItem;
import net.mcreator.gochiken.item.QuartzChikenItem;
import net.mcreator.gochiken.item.QuartzChickenSeedItem;
import net.mcreator.gochiken.item.PurpleDiamondItem;
import net.mcreator.gochiken.item.PurpleDiamond2Item;
import net.mcreator.gochiken.item.PupleChikenItem;
import net.mcreator.gochiken.item.PinkChikenItem;
import net.mcreator.gochiken.item.OrangeChikenItem;
import net.mcreator.gochiken.item.ObsidianChickenSeedItem;
import net.mcreator.gochiken.item.ObsidianChickenItem;
import net.mcreator.gochiken.item.NiwatorinoBenItem;
import net.mcreator.gochiken.item.NetutoItem;
import net.mcreator.gochiken.item.NethrrackChieckenSeedItem;
import net.mcreator.gochiken.item.NethrrackChieckenItem;
import net.mcreator.gochiken.item.NetherwartChikenItem;
import net.mcreator.gochiken.item.NetherWartChickenSeedItem;
import net.mcreator.gochiken.item.MagmaCreamChickenSeedItem;
import net.mcreator.gochiken.item.MagmaCreamChickenItem;
import net.mcreator.gochiken.item.MagentaChikenItem;
import net.mcreator.gochiken.item.LogChikenItem;
import net.mcreator.gochiken.item.LimeChikenItem;
import net.mcreator.gochiken.item.LightGrayChikenItem;
import net.mcreator.gochiken.item.LightBlueChikenItem;
import net.mcreator.gochiken.item.LeatherChickenSeedItem;
import net.mcreator.gochiken.item.LeatherChickenItem;
import net.mcreator.gochiken.item.LavaeggItem;
import net.mcreator.gochiken.item.LavaChikenItem;
import net.mcreator.gochiken.item.LavaChickenSeedItem;
import net.mcreator.gochiken.item.LapisChikenItem;
import net.mcreator.gochiken.item.IronChikenItem;
import net.mcreator.gochiken.item.IronChickenSeedItem;
import net.mcreator.gochiken.item.InkChikenItem;
import net.mcreator.gochiken.item.GunpowderChickenSeedItem;
import net.mcreator.gochiken.item.GunpowderChickenItem;
import net.mcreator.gochiken.item.GrayChikenItem;
import net.mcreator.gochiken.item.GoldChikenItem;
import net.mcreator.gochiken.item.GoldChickenSeedItem;
import net.mcreator.gochiken.item.GoItem;
import net.mcreator.gochiken.item.GlowstoneChikenItem;
import net.mcreator.gochiken.item.GloingItem;
import net.mcreator.gochiken.item.GloestnoeChickenSeedItem;
import net.mcreator.gochiken.item.GlassChikenItem;
import net.mcreator.gochiken.item.GlassChickenSeedItem;
import net.mcreator.gochiken.item.GhastChickenSeedItem;
import net.mcreator.gochiken.item.GhastChickenItem;
import net.mcreator.gochiken.item.FlintChokenItem;
import net.mcreator.gochiken.item.FlintChickenseedItem;
import net.mcreator.gochiken.item.EnderChikenItem;
import net.mcreator.gochiken.item.EnderChickenSeedItem;
import net.mcreator.gochiken.item.EmeraldChickenSeedItem;
import net.mcreator.gochiken.item.EmeraldChickenItem;
import net.mcreator.gochiken.item.EggChickenSeedItem;
import net.mcreator.gochiken.item.EggChickenItem;
import net.mcreator.gochiken.item.Egg64Item;
import net.mcreator.gochiken.item.DortChickenSeedItem;
import net.mcreator.gochiken.item.DirtChickenItem;
import net.mcreator.gochiken.item.DiamondChikenItem;
import net.mcreator.gochiken.item.DiamondChickenSeedItem;
import net.mcreator.gochiken.item.DiamondChickenItem;
import net.mcreator.gochiken.item.CyanChikenItem;
import net.mcreator.gochiken.item.Cushonmaterial2Item;
import net.mcreator.gochiken.item.CushionmaterialItem;
import net.mcreator.gochiken.item.CopperchickenkidItem;
import net.mcreator.gochiken.item.CopperchickenItem;
import net.mcreator.gochiken.item.CooperChickenSeedItem;
import net.mcreator.gochiken.item.CooperChickenItem;
import net.mcreator.gochiken.item.ColaChickenSeedItem;
import net.mcreator.gochiken.item.CoalChikenItem;
import net.mcreator.gochiken.item.ClayChikenItem;
import net.mcreator.gochiken.item.ClayChickenSeedItem;
import net.mcreator.gochiken.item.ChieknSeed4Item;
import net.mcreator.gochiken.item.ChickenSeedLV2Item;
import net.mcreator.gochiken.item.ChickenSeed6Item;
import net.mcreator.gochiken.item.ChickenSeed5Item;
import net.mcreator.gochiken.item.ChickenSeed3Item;
import net.mcreator.gochiken.item.ChiCkenSeed1Item;
import net.mcreator.gochiken.item.CactusChikenItem;
import net.mcreator.gochiken.item.BrownChikenItem;
import net.mcreator.gochiken.item.BoneChikenItem;
import net.mcreator.gochiken.item.BoneBagItem;
import net.mcreator.gochiken.item.BlueIngotItem;
import net.mcreator.gochiken.item.BlazechickenItem;
import net.mcreator.gochiken.item.BlazeChickenSeedItem;
import net.mcreator.gochiken.GochickenMod;

public class GochickenModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, GochickenMod.MODID);
	public static final RegistryObject<Item> GO = REGISTRY.register("go", () -> new GoItem());
	public static final RegistryObject<Item> NETUTO = REGISTRY.register("netuto", () -> new NetutoItem());
	public static final RegistryObject<Item> LOG_CHIKEN = REGISTRY.register("log_chiken", () -> new LogChikenItem());
	public static final RegistryObject<Item> FLINT_CHOKEN = REGISTRY.register("flint_choken", () -> new FlintChokenItem());
	public static final RegistryObject<Item> SAND_CHOKEN = REGISTRY.register("sand_choken", () -> new SandChokenItem());
	public static final RegistryObject<Item> BONE_CHIKEN = REGISTRY.register("bone_chiken", () -> new BoneChikenItem());
	public static final RegistryObject<Item> COPPERCHICKEN = REGISTRY.register("copperchicken", () -> new CopperchickenItem());
	public static final RegistryObject<Item> COPPERCHICKENKID = REGISTRY.register("copperchickenkid", () -> new CopperchickenkidItem());
	public static final RegistryObject<Item> GORWER_LV_1 = block(GochickenModBlocks.GORWER_LV_1);
	public static final RegistryObject<Item> LAYER_1 = block(GochickenModBlocks.LAYER_1);
	public static final RegistryObject<Item> ROOST = block(GochickenModBlocks.ROOST);
	public static final RegistryObject<Item> LAPIS_CHIKEN = REGISTRY.register("lapis_chiken", () -> new LapisChikenItem());
	public static final RegistryObject<Item> INK_CHIKEN = REGISTRY.register("ink_chiken", () -> new InkChikenItem());
	public static final RegistryObject<Item> MAGENTA_CHIKEN = REGISTRY.register("magenta_chiken", () -> new MagentaChikenItem());
	public static final RegistryObject<Item> LIME_CHIKEN = REGISTRY.register("lime_chiken", () -> new LimeChikenItem());
	public static final RegistryObject<Item> YELLOW_CHIKEN = REGISTRY.register("yellow_chiken", () -> new YellowChikenItem());
	public static final RegistryObject<Item> PUPLE_CHIKEN = REGISTRY.register("puple_chiken", () -> new PupleChikenItem());
	public static final RegistryObject<Item> CACTUS_CHIKEN = REGISTRY.register("cactus_chiken", () -> new CactusChikenItem());
	public static final RegistryObject<Item> LIGHT_GRAY_CHIKEN = REGISTRY.register("light_gray_chiken", () -> new LightGrayChikenItem());
	public static final RegistryObject<Item> LIGHT_BLUE_CHIKEN = REGISTRY.register("light_blue_chiken", () -> new LightBlueChikenItem());
	public static final RegistryObject<Item> CYAN_CHIKEN = REGISTRY.register("cyan_chiken", () -> new CyanChikenItem());
	public static final RegistryObject<Item> RED_CHIKEN = REGISTRY.register("red_chiken", () -> new RedChikenItem());
	public static final RegistryObject<Item> PINK_CHIKEN = REGISTRY.register("pink_chiken", () -> new PinkChikenItem());
	public static final RegistryObject<Item> ORANGE_CHIKEN = REGISTRY.register("orange_chiken", () -> new OrangeChikenItem());
	public static final RegistryObject<Item> GRAY_CHIKEN = REGISTRY.register("gray_chiken", () -> new GrayChikenItem());
	public static final RegistryObject<Item> BROWN_CHIKEN = REGISTRY.register("brown_chiken", () -> new BrownChikenItem());
	public static final RegistryObject<Item> BREEDER = block(GochickenModBlocks.BREEDER);
	public static final RegistryObject<Item> IRON_CHIKEN = REGISTRY.register("iron_chiken", () -> new IronChikenItem());
	public static final RegistryObject<Item> REDSTONE_CHIKEN = REGISTRY.register("redstone_chiken", () -> new RedstoneChikenItem());
	public static final RegistryObject<Item> GOLD_CHIKEN = REGISTRY.register("gold_chiken", () -> new GoldChikenItem());
	public static final RegistryObject<Item> QUARTZ_CHIKEN = REGISTRY.register("quartz_chiken", () -> new QuartzChikenItem());
	public static final RegistryObject<Item> GLASS_CHIKEN = REGISTRY.register("glass_chiken", () -> new GlassChikenItem());
	public static final RegistryObject<Item> DIAMOND_CHIKEN = REGISTRY.register("diamond_chiken", () -> new DiamondChikenItem());
	public static final RegistryObject<Item> GLOWSTONE_CHIKEN = REGISTRY.register("glowstone_chiken", () -> new GlowstoneChikenItem());
	public static final RegistryObject<Item> NETHERWART_CHIKEN = REGISTRY.register("netherwart_chiken", () -> new NetherwartChikenItem());
	public static final RegistryObject<Item> ENDER_CHIKEN = REGISTRY.register("ender_chiken", () -> new EnderChikenItem());
	public static final RegistryObject<Item> SNOWBALL = REGISTRY.register("snowball", () -> new SnowballItem());
	public static final RegistryObject<Item> CLAY_CHIKEN = REGISTRY.register("clay_chiken", () -> new ClayChikenItem());
	public static final RegistryObject<Item> SILME_CHIKEN = REGISTRY.register("silme_chiken", () -> new SilmeChikenItem());
	public static final RegistryObject<Item> COAL_CHIKEN = REGISTRY.register("coal_chiken", () -> new CoalChikenItem());
	public static final RegistryObject<Item> LAVA_CHIKEN = REGISTRY.register("lava_chiken", () -> new LavaChikenItem());
	public static final RegistryObject<Item> LAVAEGG = REGISTRY.register("lavaegg", () -> new LavaeggItem());
	public static final RegistryObject<Item> NIWATORINO_BEN = REGISTRY.register("niwatorino_ben", () -> new NiwatorinoBenItem());
	public static final RegistryObject<Item> PEI_HE_JI = block(GochickenModBlocks.PEI_HE_JI);
	public static final RegistryObject<Item> R_LOG_CHICKEN_SEED = REGISTRY.register("r_log_chicken_seed", () -> new RLogChickenSeedItem());
	public static final RegistryObject<Item> CHI_CKEN_SEED_1 = REGISTRY.register("chi_cken_seed_1", () -> new ChiCkenSeed1Item());
	public static final RegistryObject<Item> SAND_CHICKEN_SEED = REGISTRY.register("sand_chicken_seed", () -> new SandChickenSeedItem());
	public static final RegistryObject<Item> FLINT_CHICKENSEED = REGISTRY.register("flint_chickenseed", () -> new FlintChickenseedItem());
	public static final RegistryObject<Item> WHITE_CHICKEN_SEED = REGISTRY.register("white_chicken_seed", () -> new WhiteChickenSeedItem());
	public static final RegistryObject<Item> COLA_CHICKEN_SEED = REGISTRY.register("cola_chicken_seed", () -> new ColaChickenSeedItem());
	public static final RegistryObject<Item> CHICKEN_SEED_LV_2 = REGISTRY.register("chicken_seed_lv_2", () -> new ChickenSeedLV2Item());
	public static final RegistryObject<Item> CLAY_CHICKEN_SEED = REGISTRY.register("clay_chicken_seed", () -> new ClayChickenSeedItem());
	public static final RegistryObject<Item> IRON_CHICKEN_SEED = REGISTRY.register("iron_chicken_seed", () -> new IronChickenSeedItem());
	public static final RegistryObject<Item> CHICKEN_SEED_3 = REGISTRY.register("chicken_seed_3", () -> new ChickenSeed3Item());
	public static final RegistryObject<Item> DIRT_CHICKEN = REGISTRY.register("dirt_chicken", () -> new DirtChickenItem());
	public static final RegistryObject<Item> DORT_CHICKEN_SEED = REGISTRY.register("dort_chicken_seed", () -> new DortChickenSeedItem());
	public static final RegistryObject<Item> GUNPOWDER_CHICKEN = REGISTRY.register("gunpowder_chicken", () -> new GunpowderChickenItem());
	public static final RegistryObject<Item> GUNPOWDER_CHICKEN_SEED = REGISTRY.register("gunpowder_chicken_seed", () -> new GunpowderChickenSeedItem());
	public static final RegistryObject<Item> SLIME_CHICKEN_SEED = REGISTRY.register("slime_chicken_seed", () -> new SlimeChickenSeedItem());
	public static final RegistryObject<Item> RED_STONE_CHICKEN_SEED = REGISTRY.register("red_stone_chicken_seed", () -> new RedStoneChickenSeedItem());
	public static final RegistryObject<Item> STRING_CHICKEN = REGISTRY.register("string_chicken", () -> new StringChickenItem());
	public static final RegistryObject<Item> STRING_CHICKEN_SEED = REGISTRY.register("string_chicken_seed", () -> new StringChickenSeedItem());
	public static final RegistryObject<Item> LEATHER_CHICKEN = REGISTRY.register("leather_chicken", () -> new LeatherChickenItem());
	public static final RegistryObject<Item> LEATHER_CHICKEN_SEED = REGISTRY.register("leather_chicken_seed", () -> new LeatherChickenSeedItem());
	public static final RegistryObject<Item> COOPER_CHICKEN = REGISTRY.register("cooper_chicken", () -> new CooperChickenItem());
	public static final RegistryObject<Item> COOPER_CHICKEN_SEED = REGISTRY.register("cooper_chicken_seed", () -> new CooperChickenSeedItem());
	public static final RegistryObject<Item> QUARTZ_CHICKEN_SEED = REGISTRY.register("quartz_chicken_seed", () -> new QuartzChickenSeedItem());
	public static final RegistryObject<Item> GLASS_CHICKEN_SEED = REGISTRY.register("glass_chicken_seed", () -> new GlassChickenSeedItem());
	public static final RegistryObject<Item> GLOESTNOE_CHICKEN_SEED = REGISTRY.register("gloestnoe_chicken_seed", () -> new GloestnoeChickenSeedItem());
	public static final RegistryObject<Item> NETHER_WART_CHICKEN_SEED = REGISTRY.register("nether_wart_chicken_seed", () -> new NetherWartChickenSeedItem());
	public static final RegistryObject<Item> GOLD_CHICKEN_SEED = REGISTRY.register("gold_chicken_seed", () -> new GoldChickenSeedItem());
	public static final RegistryObject<Item> CHIEKN_SEED_4 = REGISTRY.register("chiekn_seed_4", () -> new ChieknSeed4Item());
	public static final RegistryObject<Item> SNOWBAKK_CHICKEN_SEED = REGISTRY.register("snowbakk_chicken_seed", () -> new SnowbakkChickenSeedItem());
	public static final RegistryObject<Item> NETHRRACK_CHIECKEN = REGISTRY.register("nethrrack_chiecken", () -> new NethrrackChieckenItem());
	public static final RegistryObject<Item> NETHRRACK_CHIECKEN_SEED = REGISTRY.register("nethrrack_chiecken_seed", () -> new NethrrackChieckenSeedItem());
	public static final RegistryObject<Item> LAVA_CHICKEN_SEED = REGISTRY.register("lava_chicken_seed", () -> new LavaChickenSeedItem());
	public static final RegistryObject<Item> BLAZECHICKEN = REGISTRY.register("blazechicken", () -> new BlazechickenItem());
	public static final RegistryObject<Item> BLAZE_CHICKEN_SEED = REGISTRY.register("blaze_chicken_seed", () -> new BlazeChickenSeedItem());
	public static final RegistryObject<Item> MAGMA_CREAM_CHICKEN = REGISTRY.register("magma_cream_chicken", () -> new MagmaCreamChickenItem());
	public static final RegistryObject<Item> MAGMA_CREAM_CHICKEN_SEED = REGISTRY.register("magma_cream_chicken_seed", () -> new MagmaCreamChickenSeedItem());
	public static final RegistryObject<Item> DIAMOND_CHICKEN = REGISTRY.register("diamond_chicken", () -> new DiamondChickenItem());
	public static final RegistryObject<Item> DIAMOND_CHICKEN_SEED = REGISTRY.register("diamond_chicken_seed", () -> new DiamondChickenSeedItem());
	public static final RegistryObject<Item> CHICKEN_SEED_5 = REGISTRY.register("chicken_seed_5", () -> new ChickenSeed5Item());
	public static final RegistryObject<Item> GLOING = REGISTRY.register("gloing", () -> new GloingItem());
	public static final RegistryObject<Item> ZNIC_CHICKEN = REGISTRY.register("znic_chicken", () -> new ZnicChickenItem());
	public static final RegistryObject<Item> ZNIC_CHICKEN_SEED = REGISTRY.register("znic_chicken_seed", () -> new ZnicChickenSeedItem());
	public static final RegistryObject<Item> ZNIC_INGOT = REGISTRY.register("znic_ingot", () -> new ZnicIngotItem());
	public static final RegistryObject<Item> ENDER_CHICKEN_SEED = REGISTRY.register("ender_chicken_seed", () -> new EnderChickenSeedItem());
	public static final RegistryObject<Item> EGG_CHICKEN = REGISTRY.register("egg_chicken", () -> new EggChickenItem());
	public static final RegistryObject<Item> EGG_CHICKEN_SEED = REGISTRY.register("egg_chicken_seed", () -> new EggChickenSeedItem());
	public static final RegistryObject<Item> CHICKEN_SEED_6 = REGISTRY.register("chicken_seed_6", () -> new ChickenSeed6Item());
	public static final RegistryObject<Item> EMERALD_CHICKEN = REGISTRY.register("emerald_chicken", () -> new EmeraldChickenItem());
	public static final RegistryObject<Item> EMERALD_CHICKEN_SEED = REGISTRY.register("emerald_chicken_seed", () -> new EmeraldChickenSeedItem());
	public static final RegistryObject<Item> XP_CHICKEN = REGISTRY.register("xp_chicken", () -> new XpChickenItem());
	public static final RegistryObject<Item> XP_CHICKEN_SEED = REGISTRY.register("xp_chicken_seed", () -> new XpChickenSeedItem());
	public static final RegistryObject<Item> WATER_CHICKEN = REGISTRY.register("water_chicken", () -> new WaterChickenItem());
	public static final RegistryObject<Item> WATER_CHICKEN_SEED = REGISTRY.register("water_chicken_seed", () -> new WaterChickenSeedItem());
	public static final RegistryObject<Item> OBSIDIAN_CHICKEN = REGISTRY.register("obsidian_chicken", () -> new ObsidianChickenItem());
	public static final RegistryObject<Item> OBSIDIAN_CHICKEN_SEED = REGISTRY.register("obsidian_chicken_seed", () -> new ObsidianChickenSeedItem());
	public static final RegistryObject<Item> BONE_BAG = REGISTRY.register("bone_bag", () -> new BoneBagItem());
	public static final RegistryObject<Item> ROTTEN_FLESH_BAG = REGISTRY.register("rotten_flesh_bag", () -> new RottenFleshBagItem());
	public static final RegistryObject<Item> BLUE_INGOT = REGISTRY.register("blue_ingot", () -> new BlueIngotItem());
	public static final RegistryObject<Item> EGG_64 = REGISTRY.register("egg_64", () -> new Egg64Item());
	public static final RegistryObject<Item> COMPRESSOR = block(GochickenModBlocks.COMPRESSOR);
	public static final RegistryObject<Item> CUSHIONMATERIAL = REGISTRY.register("cushionmaterial", () -> new CushionmaterialItem());
	public static final RegistryObject<Item> CUSHONMATERIAL_2 = REGISTRY.register("cushonmaterial_2", () -> new Cushonmaterial2Item());
	public static final RegistryObject<Item> PURPLE_DIAMOND = REGISTRY.register("purple_diamond", () -> new PurpleDiamondItem());
	public static final RegistryObject<Item> PURPLE_DIAMOND_2 = REGISTRY.register("purple_diamond_2", () -> new PurpleDiamond2Item());
	public static final RegistryObject<Item> GHAST_CHICKEN = REGISTRY.register("ghast_chicken", () -> new GhastChickenItem());
	public static final RegistryObject<Item> GHAST_CHICKEN_SEED = REGISTRY.register("ghast_chicken_seed", () -> new GhastChickenSeedItem());
	public static final RegistryObject<Item> SEALANTERN_CHICKEN = REGISTRY.register("sealantern_chicken", () -> new SealanternChickenItem());
	public static final RegistryObject<Item> SEALANTERN_CHICKEN_SEED = REGISTRY.register("sealantern_chicken_seed", () -> new SealanternChickenSeedItem());
	public static final RegistryObject<Item> SEED_MARKER = block(GochickenModBlocks.SEED_MARKER);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
